INSERT INTO DEPARTAMENTOS(CODIGO, DESCRICAO) VALUES ('TI', 'TECNOLOGIA DA INFORMACAO');
INSERT INTO DEPARTAMENTOS(CODIGO, DESCRICAO) VALUES ('RH', 'RECURSOS HUMANOS');
INSERT INTO DEPARTAMENTOS(CODIGO, DESCRICAO) VALUES ('COM', 'COMERCIAL');
INSERT INTO DEPARTAMENTOS(CODIGO, DESCRICAO) VALUES ('AT', 'ATENDIMENTO');

INSERT INTO FUNCIONARIOS(CPF, NOME, COD_DEPTO) VALUES (22334455667, 'LINUX TORVALDS', 'TI');
INSERT INTO FUNCIONARIOS(CPF, NOME, COD_DEPTO) VALUES (33445566778, 'ALAN TURING', 'TI');
INSERT INTO FUNCIONARIOS(CPF, NOME, COD_DEPTO) VALUES (44556677888, 'KEVIN MITNICK', 'TI');
INSERT INTO FUNCIONARIOS(CPF, NOME, COD_DEPTO) VALUES (11220099888, 'SANSA STARK', 'RH');
INSERT INTO FUNCIONARIOS(CPF, NOME, COD_DEPTO) VALUES (88998877666, 'ROB STARK', 'RH');
INSERT INTO FUNCIONARIOS(CPF, NOME, COD_DEPTO) VALUES (99877665544, 'FRODO BAGGINS', 'COM');
INSERT INTO FUNCIONARIOS(CPF, NOME, COD_DEPTO) VALUES (22555555667, 'GANDALF', 'COM');
INSERT INTO FUNCIONARIOS(CPF, NOME, COD_DEPTO) VALUES (88776655444, 'ARAGORN', 'COM');
INSERT INTO FUNCIONARIOS(CPF, NOME, COD_DEPTO) VALUES (11111122233, 'JOHN SNOW', 'AT');
INSERT INTO FUNCIONARIOS(CPF, NOME, COD_DEPTO) VALUES (99881122335, 'GALADRIEL', 'AT');
